package io.github.ckofa.filewatcher.model;


/**
 * Defines a contract for observers that listen for file system events.
 * <p>
 * This interface is a key component of the Observer design pattern, enabling a
 * loosely-coupled architecture. Multiple handlers implementing this interface
 * can react to events generated by a single source (e.g., a file monitoring service),
 * promoting extensibility.
 *
 * @see CustomWatchEvent
 * @see MessageSenderObserver
 */
public interface WatchEventObserver {

    /**
     * Invoked when a new file system event occurs.
     *
     * @param watchEvent the event object containing detailed information about the file system change.
     */
    void onEvent(CustomWatchEvent watchEvent);
}
